- hosts: localhost
  vars_files:
          - /task4/credentials.yml

  tasks:
  - name: provision of loadbalancer
  ec2_instance:
          region: ap-south-1
          image_id: ami-04b1ddd35fd71475a
          instance_type: t2.micro
          vpc_subnet_id: subnet-ec363f84
          security_group: sg-63a60204
          key_name: load
          name: ansible
          state: present
          aws_access_key: "{{ my access }}"
          aws_secret_key: "{{ my secret }}"
  - name: provision of webserver1
  ec2_instance:
          region: ap-south-1
          image_id: ami-04b1ddd35fd71475a
          instance_type: t2.micro
          vpc_subnet_id: subnet-ec363f84
          security_group: sg-63a60204
          key_name: load
          name: webserver
          state: present
          aws_access_key: "{{ my access }}"
          aws_secret_key: "{{ my secret }}"
  - name: provision of webserver3
  ec2_instance:
          region: ap-south-1
          image_id: ami-04b1ddd35fd71475a
          instance_type: t2.micro
          vpc_subnet_id: subnet-ec363f84
          security_group: sg-63a60204
          key_name: load
          name: webserver
          state: present
          aws_access_key: "{{ my access }}"
          aws_secret_key: "{{ my secret }}"
